Product.create(name:"えんがわ",price:100,genre:"nigiri",stocks:100,comments:"エンガワです。",count:1,filename:"engawa-ac.jpg")
Product.create(name:"帆立",price:100,genre:"nigiri",stocks:100,comments:"帆立です。",count:1,filename:"hotate-ac.jpg")
Product.create(name:"いくら",price:100,genre:"nigiri",stocks:100,comments:"イクラです。",count:1,filename:"ikura-ac.jpg")
Product.create(name:"稲荷",price:100,genre:"nigiri",stocks:100,comments:"稲荷寿司です。",count:1,filename:"inari-ac.jpg")
Product.create(name:"穴子",price:100,genre:"nigiri",stocks:100,comments:"アナゴです。",count:1,filename:"anago-ac.jpg")
Product.create(name:"甘海老",price:100,genre:"nigiri",stocks:100,comments:"甘エビです。",count:1,filename:"amaebi-ac.jpg")
Product.create(name:"炙りサーモン",price:100,genre:"nigiri",stocks:100,comments:"炙りサーモンです。",count:1,filename:"aburi-sa-mon-pakutaso.jpg")
Product.create(name:"炙り帆立",price:100,genre:"nigiri",stocks:100,comments:"炙り帆立です。",count:1,filename:"aburihotate-ac.jpg")
Product.create(name:"甘海老",price:100,genre:"nigiri",stocks:100,comments:"甘エビです。",count:1,filename:"amaebi-ac.jpg")
Product.create(name:"中トロ",price:100,genre:"nigiri",stocks:100,comments:"中トロです。",count:1,filename:"chuutoro-ac.jpg")

Product.create(name:"中トロ",price:100,genre:"nigiri",stocks:100,comments:"中トロです。",count:1,filename:"a-ac.jpg")
Product.create(name:"中トロ",price:100,genre:"nigiri",stocks:100,comments:"中トロです。",count:1,filename:"amaebi-ac.jpg")
Product.create(name:"中トロ",price:100,genre:"nigiri",stocks:100,comments:"中トロです。",count:1,filename:"amaebi-ac.jpg")
Product.create(name:"中トロ",price:100,genre:"nigiri",stocks:100,comments:"中トロです。",count:1,filename:"amaebi-ac.jpg")
Product.create(name:"中トロ",price:100,genre:"nigiri",stocks:100,comments:"中トロです。",count:1,filename:"amaebi-ac.jpg")
Product.create(name:"中トロ",price:100,genre:"nigiri",stocks:100,comments:"中トロです。",count:1,filename:"amaebi-ac.jpg")
Product.create(name:"中トロ",price:100,genre:"nigiri",stocks:100,comments:"中トロです。",count:1,filename:"amaebi-ac.jpg")
Product.create(name:"中トロ",price:100,genre:"nigiri",stocks:100,comments:"中トロです。",count:1,filename:"amaebi-ac.jpg")
Product.create(name:"中トロ",price:100,genre:"nigiri",stocks:100,comments:"中トロです。",count:1,filename:"amaebi-ac.jpg")
Product.create(name:"中トロ",price:100,genre:"nigiri",stocks:100,comments:"中トロです。",count:1,filename:"amaebi-ac.jpg")


User.create(name:"Yuji Teshima", email:"yuji@cakeshop.jp", pass:"pass")

