Product.create(name:"えんがわ",price:100,genre:"nigiri",stocks:100,comments:"エンガワです。",count:1,filename:"engawa-ac.jpg")
Product.create(name:"帆立",price:100,genre:"nigiri",stocks:100,comments:"帆立です。",count:1,filename:"hotate-ac.jpg")
Product.create(name:"いくら",price:100,genre:"nigiri",stocks:100,comments:"イクラです。",count:1,filename:"ikura-ac.jpg")
Product.create(name:"稲荷",price:100,genre:"nigiri",stocks:100,comments:"稲荷寿司です。",count:1,filename:"inari-ac.jpg")
Product.create(name:"穴子",price:100,genre:"nigiri",stocks:100,comments:"アナゴです。",count:1,filename:"anago-ac.jpg")
Product.create(name:"甘海老",price:100,genre:"nigiri",stocks:100,comments:"甘エビです。",count:1,filename:"amaebi-ac.jpg")
Product.create(name:"炙りサーモン",price:100,genre:"nigiri",stocks:100,comments:"炙りサーモンです。",count:1,filename:"aburi-sa-mon-pakutaso.jpg")
Product.create(name:"炙り帆立",price:100,genre:"nigiri",stocks:100,comments:"炙り帆立です。",count:1,filename:"aburihotate-ac.jpg")
Product.create(name:"甘海老",price:100,genre:"nigiri",stocks:100,comments:"甘エビです。",count:1,filename:"amaebi-ac.jpg")
Product.create(name:"中トロ",price:100,genre:"nigiri",stocks:100,comments:"中トロです。",count:1,filename:"chuutoro-ac.jpg")
Product.create(name:"アジ",price:100,genre:"nigiri",stocks:100,comments:"アジです。",count:1,filename:"aji1-ac.jpg")
Product.create(name:"コハダ",price:100,genre:"nigiri",stocks:100,comments:"コハダです。",count:1,filename:"kohada-ac.jpg")
Product.create(name:"生蟹",price:100,genre:"nigiri",stocks:100,comments:"生蟹です。",count:1,filename:"amaebi-ac.jpg")
Product.create(name:"まぐろ赤身",price:100,genre:"nigiri",stocks:100,comments:"赤身です。",count:1,filename:"maguro1-ac.jpg")
Product.create(name:"鱒の寿司",price:100,genre:"nigiri",stocks:100,comments:"鱒の寿司です。",count:1,filename:"masu-ac.jpg")
Product.create(name:"鯛",price:100,genre:"nigiri",stocks:100,comments:"鯛です。",count:1,filename:"tai-ac.jpg")
Product.create(name:"エンガワ",price:100,genre:"nigiri",stocks:100,comments:"エンガワです。",count:1,filename:"engawa-ac.jpg")
Product.create(name:"カッパ巻き",price:100,genre:"nigiri",stocks:100,comments:"カッパ巻です。",count:1,filename:"kappa-ac.jpg")
Product.create(name:"海老",price:100,genre:"nigiri",stocks:100,comments:"海老です。",count:1,filename:"ebi-ac.jpg")

Product.create(name:"海鮮丼1",price:100,genre:"kaisen",stocks:100,comments:"海鮮丼です。",count:1,filename:"kaisen1-ac.jpg")
Product.create(name:"海鮮丼2",price:100,genre:"kaisen",stocks:100,comments:"海鮮丼です",count:1,filename:"kaisen1-pixabay.jpg")
Product.create(name:"鰹鮪丼",price:100,genre:"kaisen",stocks:100,comments:"海鮮丼です",count:1,filename:"katsuo-magurodon-ac.jpg")
Product.create(name:"サーモン丼",price:100,genre:"kaisen",stocks:100,comments:"海鮮丼です",count:1,filename:"samon-ikuradon-ac.jpg")
Product.create(name:"鉄火丼",price:100,genre:"kaisen",stocks:100,comments:"海鮮丼です",count:1,filename:"tekkadon-ac.jpg")
Product.create(name:"山盛いくら丼",price:100,genre:"kaisen",stocks:100,comments:"海鮮丼です",count:1,filename:"yamamori-ikura-ac.jpg")
Product.create(name:"山かけ丼",price:100,genre:"kaisen",stocks:100,comments:"海鮮丼です",count:1,filename:"yamakake-ac.jpg")
Product.create(name:"いくら丼",price:100,genre:"kaisen",stocks:100,comments:"海鮮丼です",count:1,filename:"ikura2-ac.jpg")
Product.create(name:"しらす丼",price:100,genre:"kaisen",stocks:100,comments:"海鮮丼です",count:1,filename:"sirasudon-ac.jpg")
Product.create(name:"鯛丼",price:100,genre:"kaisen",stocks:100,comments:"海鮮丼です",count:1,filename:"taidon-ac.jpg")

Product.create(name:"蟹汁",price:100,genre:"siru",stocks:100,comments:"汁物です",count:1,filename:"sirasudon-ac.jpg")
Product.create(name:"あさり汁",price:100,genre:"siru",stocks:100,comments:"汁物です",count:1,filename:"asari-asinari.jpg")
Product.create(name:"ニラわかめ汁",price:100,genre:"siru",stocks:100,comments:"汁物です",count:1,filename:"nirawakame-asinari.jpg")
Product.create(name:"鯛汁",price:100,genre:"siru",stocks:100,comments:"汁物です",count:1,filename:"taiziru-pixabay.jpg")
Product.create(name:"豚汁",price:100,genre:"siru",stocks:100,comments:"汁物です",count:1,filename:"tonziru-asinari.jpg")

Product.create(name:"揚巻",price:100,genre:"sousaku",stocks:100,comments:"創作・新作です",count:1,filename:"sinsaku1-unsplash.jpg")
Product.create(name:"手毬寿司",price:100,genre:"sousaku",stocks:100,comments:"創作・新作です",count:1,filename:"sinsaku2-ashinari.jpg")




User.create(name:"Yuji Teshima", email:"yuji@cakeshop.jp", pass:"pass")

